# This workflow will build a docker image and publish it to Docker Hub.
#
# To configure this workflow:

# 1. Set up secrets in the repository settings:
#    a. DOCKER_USERNAME with the name of the project.
#    b. DOCKER_PASSWORD with the service account email.
#
# 2. Change the values for the IMAGE, IMAGE_WITH_VERSION environment variables (below).

name: Build and Publish

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: karimoff/website
  IMAGE_WITH_VERSION: $IMAGE:$GITHUB_SHA

jobs:
  setup-build-publish:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Authenticate docker
      - name: Login
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Build the image with tag
      - name: Build, Tag
        run: |
          docker build -t $IMAGE:$GITHUB_SHA -f ./flask/Dockerfile ./flask
          docker tag $IMAGE:$GITHUB_SHA $IMAGE:latest

      # Push the image to Docker Hub
      - name: Publish
        run: |
          docker push $IMAGE:$GITHUB_SHA
          docker push $IMAGE:latest
